[general]

import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]

padding.x = 10
padding.y = 10
decorations = "None"
option_as_alt = "OnlyLeft"

[font]

normal.family = "CaskaydiaCove Nerd Font Mono"
bold.family = "CaskaydiaCove Nerd Font Mono"
italic.family = "CaskaydiaCove Nerd Font Mono"
bold_italic.family = "CaskaydiaCove Nerd Font"
size = 16.0
offset.y = 5

[cursor]

style.blinking = "On"
blink_interval = 500
blink_timeout = 0

[mouse]

hide_when_typing = true

