vim.opt.backup = false
vim.opt.cmdheight = 1
vim.opt.colorcolumn = '80'
vim.opt.completeopt = 'menu,menuone,noselect,fuzzy,nosort'
vim.opt.cursorline = true
vim.opt.errorbells = false
vim.opt.expandtab = true
vim.opt.ignorecase = true
vim.opt.inccommand = 'split'
vim.opt.laststatus = 2
vim.opt.list = true
vim.opt.listchars = 'tab:▸ ,trail:.'
vim.opt.number = true
vim.opt.numberwidth = 5
vim.opt.pumheight = 10
vim.opt.relativenumber = true
vim.opt.scrolloff = 5
vim.opt.shiftround = true
vim.opt.shiftwidth = 4
vim.opt.shortmess:append({ W = true, I = true, c = true, C = true })
vim.opt.sidescrolloff = 5
vim.opt.signcolumn = 'yes'
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitkeep = 'screen'
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.undodir = vim.fn.stdpath('data') .. '/undo'
vim.opt.updatetime = 300
vim.opt.virtualedit = 'onemore'
vim.opt.visualbell = true
vim.opt.winborder = 'rounded'
vim.opt.wrap = false
vim.opt.writebackup = false
